name: Ejercicio 1
on:
  push:
    branches: [ "main" ]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Saludo
        run: echo "Hola, mi nombre es Rommen J. Durand P."

      - name: Fecha y hora actual
        run: date

      - name: Sistema operativo
        run: echo "El sistema operativo es $RUNNER_OS"