name: Ejercicio 3
on:
  push:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
      
      - name: Verificación del código
        run: echo "Código verificado correctamente"

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Ejecutar Test
        run: npm test


  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Build
        run: echo "Build completado exitosamente"

      - name: Genera archivo build-info
        run: |
          date > build-info.txt
          echo "Version: 1.0.0" >> build-info.txt
# uso la v4 porque da error la v3 por deprecada
      - name: Subir Artifact
        uses: actions/upload-artifact@v34
        with:
          name: build-artifact
          path: build-info.txt